### ISSUE TITLE
Potato MUSH Client: Music Note at the End of Random Lines

### ISSUE THREAD

**Issue by bbmeltdown** [potatomushclient/potato#478]
When there's a return (%r), a music note appears in the readout. I've converted to utf-8 which got rid of a lot of music notes (every single line), but there's still many others left. 

What do I do?

**Comment by talvo** [comment]
Most likely you have the world type set to MUD rather than MUSH; Options -> Configure World, scroll down and change MU Type. (The music note is a fairly common visual representation for line-feed.)

**Comment by talvo** [comment]
Closing due to age and no follow-up.
