### ISSUE TITLE
Does +beep work with Potato?

### ISSUE THREAD

**Issue by Rilauven** [potatomushclient/potato#497]
This is a tricky question because it's probably coded differently on different mushes. I'm reasonably sure I have +beep set up correctly on the mush, but Potato won't play the sound, is there a setting for this? That's muted by default perhaps?

**Comment by talvo** [comment]
There's an option in Options -> Configure World -> Misc, but it will depend on how it's coded, yeah. Do you know either a) what codebase it's on, and/or b) what the +beep command actually sends?

You can turn on Debug Packets (in the View menu), use +beep, then add a screenshot of the DP window on here so I can see what +beep is doing.

**Comment by Rilauven** [comment]
Turned out the problem was with the mush, the configuration options were a lot more complicated than they looked.
