### ISSUE TITLE
New Bug

### ISSUE THREAD

**Issue by Eckspert** [potatomushclient/potato#507]
Basically I edited the name of one world... and created a new world... then had to force close the app. The problem started after I edited the name of the world.
```
Dev file "C:\Users\aihah\OneDrive\Desktop\potato\potato.dev" does not exist.
610 translations set for de_de.
12 translations set for en_us.
308 translations set for es.
605 translations set for hr_hr.
607 translations set for no.
584 translations set for se.
Startup Commands file "C:\Users\aihah\OneDrive\Desktop\potato\potato.startup" does not exist.
can't read "conn(5,id)": no such element in array
   can't read "conn(5,id)": no such element in array
    while executing
"if { $conn($c,id) eq "" || $conn($c,connected) != 1 } {
		return;
	}"
    (procedure "::potato::get_mushage" line 5)
    invoked from within
"::potato::get_mushage 5"
```

**Comment by talvo** [comment]
How did you edit the name of the world / add the new one? Through the normal menus inside the programme?

**Comment by Eckspert** [comment]
Yes, I changed the world name through the app itself

**Comment by talvo** [comment]
Hrm. This should be totally unrelated to changing the world name, and I have no idea how it could have happened. Closing as a heisenbug just because I have no way to debug and it must be pretty uncommon, but if you experience it again please re-report and I'll try and dig into it.
