### ISSUE TITLE
Regex Weirdness with angle brackets

### ISSUE THREAD

**Issue by fuzzyweapon** [potatomushclient/potato#527]
Okay, the given scenario is I'm trying to highlight names in various contexts.  One of those contexts is in channel chatter.  Typically the way I accomplish this is using a caseless regex event w/ a match-all like so:

`Fooman|Foo|Everyman`

This will work for almost every sample, except (and it should work) this:

`<Channel-OOC> Fooman Everyman says, "This is just a test."`

Turns out when you isolate the issue, all you have to do is remove the right angle bracket and this gets it working again.

This leads me to a conclusion that something is wrong, because this should match, at the very least, `Fooman` and angle brackets in the input shouldn't matter a lick.

**Comment by fuzzyweapon** [comment]
The only way to get around this is to use contains, which works in both scenarios.  But this is not feasible really because then you have to split up every name, nickname, last name, codename, etc into separate rules.  I like to highlight my characters and critical characters in my character's lives (to make big scenes easier).  So regex is really the proper solution.

As someone who can rack up more than a few events, it's important that I don't have an event explosion like this, because it will eventually cause performance issues (I've hit this limit before).

**Comment by fuzzyweapon** [comment]
Okay...wow, this was some weirdness with rules.  Basically what happens is if I change the color of the name before the rule to copy to spawn, it won't work.  If I change the color after, it does.  This might be by design and a limitation of how it is coded.  It's a little tricky and unintuitive that this happens, but with all the other stuff on the plate, this is small potatoes and I'm closing it.  If it turns out this causes real limitations that cannot be worked around, I will open up a clean new issue.

**Comment by talvo** [comment]
It may just be because I'm reading this after midnight, but I'm not 100% certain what the issue is (appreciate you closed it, but it does sound like a bug so I'd still like to try and look into it, at some point). It sounds like you're saying that recolouring text via an event then stops it matching in subsequent regexp events, is that right?
